Title = N-Mod Filter
Command = SkylineNModFilter.exe
Arguments = --document-path "$(DocumentPath)"
InitialDirectory = $(DocumentDir)
OutputToImmediateWindow = False
ArgsCollectorDll = SkylineNModFilterArgsCollector.dll
ArgsCollectorType = SkylineNModFilter.ArgsCollector.Collector
